baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Vikas C. Raykar'
theme = 'hugo-book'

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    style = 'monokailight'

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true
